import constants from 'react-constants';

export default constants([
  'RETRIEVEPROTOTYPELIST',
  'RETRIEVEPROTOTYPE',
  'CREATENEWPROTOTYPE',
  'CLONEPROTOTYPE',
  'EDITPROTOTYPE',
  'DELETEPROTOTYPE',
  'CREATETESTDEVICE',
  'RETRIEVEPROTOTYPETEMPLATES',
  'RETRIEVEUNITTYPES',
  'UPLOADPROTOTYPEIMAGE',
  'SETPROTOTYPETOTEMPLATE',
]);
