export const getData = t => [{
  dataChannelTypeId: 7,
  dataChannelTypeName: 'Switch',
  children: t('DC.Switch'),
  type: 1,
},
// {
//   dataChannelTypeId: 10,
//   dataChannelTypeName: "Category",
// children: t('DC.Category'),
//   type: 1,
// },
{
  dataChannelTypeId: 1,
  dataChannelTypeName: 'Integer',
  children: t('DC.Integer'),
  type: 1,
},
{
  dataChannelTypeId: 2,
  dataChannelTypeName: 'Float',
  children: t('DC.Float'),
  type: 1,
},
{
  dataChannelTypeId: 4,
  dataChannelTypeName: 'Hex',
  children: t('DC.Hex'),
  type: 1,
},
{
  dataChannelTypeId: 5,
  dataChannelTypeName: 'String',
  children: t('DC.String'),
  type: 1,
},
// {
//   dataChannelTypeId: 6,
//   dataChannelTypeName: "GPS",
// children: t('DC.GPS'),
//   type: 1,
//   configs: {},
//   configSchema: {},
// },
{
  dataChannelTypeId: 11,
  dataChannelTypeName: 'GPIO',
  children: t('DC.GPIO'),
  type: 1,
},
{
  dataChannelTypeId: 12,
  dataChannelTypeName: 'PWM',
  children: t('DC.PWM'),
  type: 1,
},
{
  dataChannelTypeId: 3,
  dataChannelTypeName: 'Switch',
  children: t('DC.Switch'),
  type: 2,
},
// {
//   dataChannelTypeId: 10,
//   dataChannelTypeName: "Category",
// children: t('DC.Category'),
//   type: 2,
// },
{
  dataChannelTypeId: 1,
  dataChannelTypeName: 'Integer',
  children: t('DC.Integer'),
  type: 2,
},
{
  dataChannelTypeId: 2,
  dataChannelTypeName: 'Float',
  children: t('DC.Float'),
  type: 2,
},
{
  dataChannelTypeId: 4,
  dataChannelTypeName: 'Hex',
  children: t('DC.Hex'),
  type: 2,
},
{
  dataChannelTypeId: 5,
  dataChannelTypeName: 'String',
  children: t('DC.String'),
  type: 2,
},
// {
//   dataChannelTypeId: 6,
//   dataChannelTypeName: "GPS",
// children: t('DC.GPS'),
//   type: 2,
//   configs: {},
//   configSchema: {},
// },
{
  dataChannelTypeId: 11,
  dataChannelTypeName: 'GPIO',
  children: t('DC.GPIO'),
  type: 2,
},
{
  dataChannelTypeId: 12,
  dataChannelTypeName: 'PWM',
  children: t('DC.PWM'),
  type: 2,
},
// {
//   dataChannelTypeId: 13,
//   dataChannelTypeName: "Analog",
// children: t('DC.Analog'),
//   type: 1,
// },
// {
//   dataChannelTypeId: 14,
//   dataChannelTypeName: "GamePad",
// children: t('DC.GamePad'),
//   type: 1,
//   configs: {},
//   configSchema: {},
// },
// {
//   dataChannelTypeId: 15,
//   dataChannelTypeName: "Image",
// children: t('DC.Image'),
//   type: 2,
//   configs: {},
//   configSchema: {},
// },
// {
//   dataChannelTypeId: 16,
//   dataChannelTypeName: "VideoStream",
// children: t('DC.VideoStream'),
//   type: 2,
//   configs: {},
//   configSchema: {},
// },
];
