export const getData = t => [{
  dataChannelTypeId: 7,
  dataChannelTypeName: t('DC.Switch'),
  type: 1,
},
// {
//   dataChannelTypeId: 10,
//   dataChannelTypeName: t("DC.Category"),
//   type: 1,
// },
{
  dataChannelTypeId: 1,
  dataChannelTypeName: t('DC.Integer'),
  type: 1,
},
{
  dataChannelTypeId: 2,
  dataChannelTypeName: t('DC.Float'),
  type: 1,
},
{
  dataChannelTypeId: 4,
  dataChannelTypeName: t('DC.Hex'),
  type: 1,
},
{
  dataChannelTypeId: 5,
  dataChannelTypeName: t('DC.String'),
  type: 1,
},
// {
//   dataChannelTypeId: 6,
//   dataChannelTypeName: t("DC.GPS"),
//   type: 1,
//   configs: {},
//   configSchema: {},
// },
{
  dataChannelTypeId: 11,
  dataChannelTypeName: t('DC.GPIO'),
  type: 1,
},
{
  dataChannelTypeId: 12,
  dataChannelTypeName: t('DC.PWM'),
  type: 1,
},
{
  dataChannelTypeId: 3,
  dataChannelTypeName: t('DC.Switch'),
  type: 2,
},
// {
//   dataChannelTypeId: 10,
//   dataChannelTypeName: t("DC.Category"),
//   type: 2,
// },
{
  dataChannelTypeId: 1,
  dataChannelTypeName: t('DC.Integer'),
  type: 2,
},
{
  dataChannelTypeId: 2,
  dataChannelTypeName: t('DC.Float'),
  type: 2,
},
{
  dataChannelTypeId: 4,
  dataChannelTypeName: t('DC.Hex'),
  type: 2,
},
{
  dataChannelTypeId: 5,
  dataChannelTypeName: t('DC.String'),
  type: 2,
},
// {
//   dataChannelTypeId: 6,
//   dataChannelTypeName: t("DC.GPS"),
//   type: 2,
//   configs: {},
//   configSchema: {},
// },
{
  dataChannelTypeId: 11,
  dataChannelTypeName: t('DC.GPIO'),
  type: 2,
},
{
  dataChannelTypeId: 12,
  dataChannelTypeName: t('DC.PWM'),
  type: 2,
},
// {
//   dataChannelTypeId: 13,
//   dataChannelTypeName: t("DC.Analog"),
//   type: 1,
// },
// {
//   dataChannelTypeId: 14,
//   dataChannelTypeName: t("DC.GamePad"),
//   type: 1,
//   configs: {},
//   configSchema: {},
// },
// {
//   dataChannelTypeId: 15,
//   dataChannelTypeName: t("DC.Image"),
//   type: 2,
//   configs: {},
//   configSchema: {},
// },
// {
//   dataChannelTypeId: 16,
//   dataChannelTypeName: t("DC.VideoStream"),
//   type: 2,
//   configs: {},
//   configSchema: {},
// },
];
