module.exports = {
  type: 'object',
  properties: {
    userId: { type: 'string' },
    email: { type: 'string' },
    userName: { type: 'string' },
    userImage: {type: 'string'},
    isActive: { type: 'boolean' },
    updatedAt: { type: 'integer' },
    createdAt: { type: 'integer' },
    isActive: { type: 'boolean' },
    isAdmin: { type: 'boolean' },
  },
  required: [
    'userId',
    'email',
    'userName',
    'userImage',
    'isActive',
    'updatedAt',
    'createdAt',
    'isActive',
    'isAdmin',
  ],
};