module.exports = {
  type: 'object',
  properties: {
    "prodName": { type: 'string' },
    "description": { type: 'string' },
    "developmentNote": { type: 'any' },
    "prodAppTypeId": { type: 'number' },
    "prodRlsStatusTypeId": { type: 'number' },
    "version": { type: 'string' },
    "displayConfigs": { type: 'array' },
    "saleReleaseDate": { type: 'any' },
    "saleDiscontinuousDate": { type: 'any' },
    "isLongConnectionNeeded": { type: 'boolean' },
    "isSerialNeeded": { type: 'boolean' },
    "isInterpreterCloudNeeded": { type: 'boolean' },
    "status": { type: 'boolean' },
    "prodImgURL": { type: 'string' },
    "prodDesc": { type: 'string' },
    "chipId": { type: 'nubmer' },
    "dataChannels": {type: 'array' },
    "triggerActions": { type: 'array' },
  },
  required: [
    "prodName",
    "description",
    "developmentNote",
    "prodAppTypeId",
    "prodRlsStatusTypeId",
    "version",
    "displayConfigs",
    "saleReleaseDate",
    "saleDiscontinuousDate",
    "isLongConnectionNeeded",
    "isSerialNeeded",
    "isInterpreterCloudNeeded",
    "status",
    "prodImgURL",
    "prodDesc",
    "chipId",
    "triggerActions",
    "dataChannels",
  ],
};