module.exports = {
  type: 'object',
  properties: {
    prototypeId: { type: 'string' },
    prototypeKey: { type: 'string' },
    prototypeName: { type: 'string' },
    prototypeDescription: { type: 'string' },
    prototypeImageURL: { type: 'string' },
    createUserId: { type: 'string' },
    version: { type: 'string' },
    isPublic: { type: 'boolean' },
    isActive: { type: 'boolean' },
    updatedAt: { type: 'integer' },
    createdAt: { type: 'integer' },
    isTemplate: { type: 'boolean' },
  },
  required: [
    'prototypeId',
    'prototypeKey',
    'prototypeName',
    'prototypeDescription',
    'prototypeImageURL',
    'createUserId',
    'version',
    'isPublic',
    'isActive',
    'isTemplate',
  ],
};