module.exports = {
  type: 'object',
  properties: {
    prototypeId: { type: 'string' },
    datachannelName: { type: 'string' },
    datachannelId: { type: 'string' },
    datachannelDescription: { type: 'string' },
    type: { type: 'number' },
    channelType: { type: 'object' },
    isHidden: { type: 'boolean' },
    format: { type: 'object' },
    createUserId: { type: 'string' },
    updatedAt: { type: 'integer' },
    createdAt: { type: 'integer' },
    isActive: { type: 'boolean' },
    hasHistory: { type: 'boolean' },
  },
  required: [
    'prototypeId',
    'datachannelId',
    'datachannelName',
    'datachannelDescription',
    'format',
    'type',
    'channelType',
    'isHidden',
    'createUserId',
    'updatedAt',
    'createdAt',
    'isActive',
    'hasHistory',
  ],
};
